fluxo_de_caixa/urls.py


from fluxo_de_caixa import views
from django.urls import path
from .views import (
    NovoPedido, NovoItemPedido, ListaVendas, AtualizarPedido, 
    EditPedido, DeletePedido, DeleteItemPedido, ListaVendaPagas,
    CaixaDepositar, CaixaSacar, Caixas, CaixasUpdate,
    ListaVendaPorUsuario, AbrirFeixarCaixa, SaidaDeMercadoria
)


urlpatterns = [
    path('', ListaVendas.as_view(), name='lista-vendas'),
    path('vendas-pagas/', ListaVendaPagas.as_view(), name='vendas_pagas'),
    path('novo-pedido/', NovoPedido.as_view(), name="novo-pedido"),
    path('atualizar-pedido/', AtualizarPedido.as_view(), name="atualizar-pedido"),
    path('novo-item-pedido/<int:venda>/', NovoItemPedido.as_view(), name="novo-item-pedido"),
    path('lista-venda-usuario/', ListaVendaPorUsuario.as_view(), name="lista-venda-usuario"),
    path('edit-pedido/<int:venda>/', EditPedido.as_view(), name="edit-pedido"),
    path('delete-item-pedido/<int:item>/', DeleteItemPedido.as_view(), name="delete-item-pedido"),
    path('delete-pedido/<int:venda>/', DeletePedido.as_view(), name="delete-pedido"),
    path('caixa-deposito/<int:id>/', CaixaDepositar.as_view(), name="caixa-deposito"),
    path('caixa-sacar/<int:id>/', CaixaSacar.as_view(), name="caixa-sacar"),
    path('abrir-feixar-caixa/<int:id>/', AbrirFeixarCaixa.as_view(), name="abrir-feixar-caixa"),
    path('caixa/', Caixas.as_view(), name="caixa"),
    path('caixa-update/<int:id>/', CaixasUpdate.as_view(), name='caixa-update'),
    path('delete-caixa/(?P<id>\d+)/', views.caixa_delete, name='delete-caixa'),
    path('saida_mercadoria/', SaidaDeMercadoria.as_view(), name='saida_mercadoria'),
]

'''
from django.urls import  path
from vendas import views
from .views import (
    ListaVendas,

)

urlpatterns = [
    path('', views.vendas),
    #path('vendas/', views.vendas),
   # path('login/', views.login),


    path('caixa/', ListaVendas.as_view(), name='lista-vendas'),
    path('vendas/', views.vendas, name= 'vendas_listarvendas'),
    path('vendas-update/(?P<id>\d+)/', views.vendas_update, name='vendas_update'),
    path('vendas-novo/', views.vendas_novo, name= 'vendas_novo'),
'''

home/urls.py
from django.urls import  path
from home import views
from .views import (
    Usuario
)

urlpatterns = [
    #path('', views.home),
    path('', views.home, name='inicio'),
    path('manual/', views.manual, name='manual'),
    path('tela_inicial/', views.TelaInicial, name='tela_inicial'),
    path('usuario/', Usuario.as_view(), name='usuario'),
]

fluxo_de_caixa/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Sum, F, FloatField
from django.db.models.signals import post_save
from django.dispatch import receiver
from produto.models import Produto
from usuarios.models import Usuarios
from pessoa.models import Funcionario, Cliente
from datetime import date
#import datetime

class Caixa(models.Model):
    nome_do_caixa = models.CharField(max_length=30)
    funcionario = models.ForeignKey(Funcionario, null=True, on_delete=models.CASCADE)
    valor_atualizado = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)
    data_hora = models.DateTimeField(default=timezone.now)

    def caixa(self):

#buscando o valor do depósuto
        depositar= self.depositar_sacar_set.all().aggregate(deposito=Sum('depositar'))
        total_do_deposito=depositar['deposito'] or 0

#buscando o valor do saque
        sacar= self.depositar_sacar_set.all().aggregate(saque =Sum('sacar'))
        total_do_saque = sacar['saque'] or 0

# calculo do saldo atual do caixa
        valor_atualizado = float(total_do_deposito) - float(total_do_saque)
        self.valor_atualizado = valor_atualizado
        Caixa.objects.filter(id=self.id).update(valor_atualizado = valor_atualizado)


    def __str__(self):
        return str(self.nome_do_caixa)+ ' - ' + str(self.funcionario)

class Depositar_sacar(models.Model):
    descricao = models.CharField(max_length=100, null=True, blank=True, verbose_name="Descrição")
    estado_do_caixa = models.CharField(max_length=10, null=True, blank=True, verbose_name="estado do caixa")
    depositar = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    venda_realizadas= models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    saldo_em_caixa = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    sacar = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    caixa = models.ForeignKey(Caixa, null=True, on_delete=models.CASCADE)
    data_hora = models.DateTimeField(default=timezone.now)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.sacar)+ ' - ' + str(self.depositar)

class Tipo_de_pagamento(models.Model):
    nome = models.CharField(max_length=30)

    def __str__(self):
        return str(self.nome)

class Venda(models.Model):
    cliente = models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    valor_com_desconto = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    desconto = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True, default=0)
    total_desconto = models.DecimalField(max_digits=9, null=True, blank=True, decimal_places=2, default=0)
    valor_recebido = models.DecimalField(max_digits=9,null=True, blank=True, decimal_places=2, default=0)
    valor_credito = models.FloatField(null=True, blank=True, default=0)
    valor_cedula = models.FloatField(null=True, blank=True, default=0)
    valor_debito = models.FloatField( null=True, blank=True, default=0)
    troco = models.DecimalField(max_digits=9, null=True, blank=True,decimal_places=2, default=0)
    tipo_de_pagamento = models.ForeignKey(Tipo_de_pagamento, null=True, on_delete=models.CASCADE)
    finalizada = models.CharField(max_length=20, blank=True, null=True)
    nfe_emitida = models.BooleanField(default=False)
    data_hora = models.DateTimeField(default=timezone.now)
    user = models.CharField(max_length=100, blank=True, null=True)
    user_2 =models.CharField(max_length=1000, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cliente) + ' - Cliente: ' + str(self.id) + ' - Valor: ' + str(self.valor)

# calculo do valor total da venda
    def calcular_total(self):
        valor_da_venda = self.itemdopedido_set.all().aggregate(
        valor=Sum((F('quantidade_de_itens') * F('produto__valor_venal')), output_field=FloatField()))
        total_produto=valor_da_venda['valor'] or 0
        self.valor = total_produto
        Venda.objects.filter(id=self.id).update(valor = total_produto)

# calculo de desconto por item
        desconto_item = self.itemdopedido_set.aggregate(
        total_item=Sum(F('quantidade_de_itens') * F('produto__valor_venal') * F('desconto')/100, output_field=FloatField()))
        desconto_por_item= desconto_item['total_item']or 0

# calculo descont da promoçao

        promocao = self.itemdopedido_set.values_list(
            'produto__id','produto__promocao__quantidade_promocional',
            'produto__valor_venal','produto__promocao__desconto',
            'produto__promocao__data_inicio', 'produto__promocao__data_termino'
            ).annotate(d=Sum('quantidade_de_itens'))

        today = date.today()
        total_promocao = 0
        total_da_venda = 0
        if promocao:
            for valor in promocao:
                if valor[4] != None and  valor[5] != None and  valor[1] != None and\
                    valor[6] >= valor[1] and valor[4] and\
                        today >=  valor[4] and today <= valor[5]:

                    calculo_promocao = float(
                        (valor[6] *  valor[2]) * valor[3] /100 or 0)

                    total_promocao +=  calculo_promocao

        total_da_venda = total_produto - desconto_por_item - total_promocao
# calculo do desconto da venda e do total da venda
        desconto_por_venda = total_da_venda * float(self.desconto)/ 100 #desconto por venda
        total_da_venda = total_da_venda - desconto_por_venda
        self.valor_com_desconto = total_da_venda
        Venda.objects.filter(id=self.id).update(valor_com_desconto=total_da_venda)

# Pagamento em crédito
        credito = self.itemdopedido_set.filter(venda__tipo_de_pagamento__id=2)

        if credito:
            self.valor_credito = total_da_venda
            Venda.objects.filter(id=self.id).update(valor_credito = total_da_venda)

#Pagamento em débito
        debito = self.itemdopedido_set.filter(venda__tipo_de_pagamento__id=3)
        if debito:
            self.valor_debito = total_da_venda
            Venda.objects.filter(id=self.id).update(valor_debito = total_da_venda)

# calculo do troco
        total_troco = 0
        if  self.valor_recebido or self.valor_debito or self.valor_credito > 0:
            total_troco = float(self.valor_recebido) + float(self.valor_debito) + float(self.valor_credito) - total_da_venda
            self.troco = float(total_troco)
            Venda.objects.filter(id=self.id).update(troco=total_troco)

# Somando do total de desconto da venda, por cada item e da promoção
        total_des=desconto_por_venda + desconto_por_item + total_promocao
        self.total_desconto = total_des
        Venda.objects.filter(id=self.id).update(total_desconto = total_des)

# valor da cedula
        valor_recebido = float(self.valor_recebido)
        if valor_recebido > 0 :
            cedula = float(self.valor_recebido)- total_troco
            self.valor_cedula = cedula
            Venda.objects.filter(id=self.id).update(valor_cedula = cedula)



class ItemDoPedido(models.Model):
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade_de_itens = models.DecimalField(max_digits=9, decimal_places=2, blank=True,default=0)
    desconto = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True,default=0)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)
    estoque_fisico_atual = models.DecimalField(
        max_digits=9, decimal_places=2, blank=True, default=0)

    def __str__(self):
        return str(self.venda.id) + ' - ' + str(self.produto.nome) + ' - ' + str(self.desconto) + ' - ' + str(self.quantidade_de_itens)  + ' - ' + str(self.produto.valor_venal)

    def saida_mercadoria(self):
        if float(self.quantidade_de_itens) == 0:
            estoque = float(
                float(self.produto.estoque) - float(self.estoque_fisico_atual))
            ItemDoPedido.objects.filter(id=self.id).update(
                quantidade_de_itens = estoque)

@receiver(post_save, sender=ItemDoPedido)
def update_quantidade_de_itens(sender, instance, **kwargs):
    instance.saida_mercadoria()

@receiver(post_save, sender=ItemDoPedido)
def update_total_saida_de_mercadoria(sender, instance, **kwargs):
    instance.produto.atualizar_estoque()

@receiver(post_save, sender=ItemDoPedido)
def update_vendas_total(sender, instance, **kwargs):
    instance.venda.calcular_total()

@receiver(post_save, sender=Venda)
def update_vendas_total2(sender, instance, **kwargs):
    instance.calcular_total()

@receiver(post_save, sender=Depositar_sacar)
def update_vendas_caixa(sender, instance, **kwargs):
    instance.caixa.caixa()

fluxo_de_caixa/forms.py
from django import forms
from .models import  Produto
from .models import ItemDoPedido

#from django.core.exceptions import ValidationError
#from django.forms import Select #CheckboxInput, ModelChoiceField, Select, ModelMultipleChoiceField, SelectMultiple
#from django.utils.translation import ugettext_lazy as _
class ItemPedidoValidacaoForm(forms.Form):
    produto_id = forms.CharField(label='Código', max_length=100)

def produtoID(valor, request):
    produto= ItemDoPedido.objects.filter(produto_id=request.POST['produto_id']) or 0
    if produto == 0:
        raise forms.ValidationError('Produto não cadastrado')

class ItemPedidoForm(forms.Form):
    produto_id = forms.CharField( validators=[produtoID, ])
    #produto_id = forms.CharField(label='Código', max_length=100)
    #busca= forms.CharField(label='Buscar produtos', max_length=100)
    #produto_id = forms.ModelMultipleChoiceField(queryset=Produto.objects.all().order_by("nome"))

    def clean_produto_id(self):
        produto = self.cleaned_data['produto_id']
        valor = Produto.objects.filter(id=produto)
        if "produto_id" not in valor:
            raise forms.ValidationError('Produto não cadastrado')
        return produto

#https://books.google.com.br/books?id=ma3_DwAAQBAJ&pg=PT439&lpg=PT439&dq=MultipleChoiceField+django+busca&source=bl&ots=Wfgox97M8B&sig=ACfU3U0GpXXmG1yV6hO6V_B0W0kfho4WdA&hl=pt-BR&sa=X&ved=2ahUKEwji59WCm4zvAhX9G7kGHd9sCVcQ6AEwEXoECBgQAw#v=onepage&q=MultipleChoiceField%20django%20busca&f=false
#https://pythonacademy.com.br/blog/desenvolva-aplicativos-para-android-ios-com-python-e-kivy
#https://data-flair.training/blogs/django-forms-handling-and-validation/
#https://django.readthedocs.io/en/stable/topics/forms/modelforms.html
#https://django.readthedocs.io/en/stable/ref/models/instances.html#validating-objects

fluxo_de_caixa/templates/buscar-produtos.html
{% extends 'base_caixa.html'%}

{% block main%}
<br>
<form class='formulario' method="GET" action="{% url 'buscar-produtos' %}">
          <label for="busca"> Buscar produto</label>

          <input style=" width:200px;" type="text" id="produt" name="produt" >
          <button style=" width:80px;" type="submit">OK</button>

</form>

<div>
    <table class="table">
      <thead>
        <tr>
          <th >Código</th>
          <th >Nome do Produto</th>
        </tr>
      </thead>
      <tbody>
        {% for produto in produtos %}
            <tr>
                <td>{{ produto.codigo }}</td>
                <td>{{ produto.nome }}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

fluxo_de_caixa/templates/caixa-update.html
{% extends 'base.html'%}
{% block main%}
<br>
  <h2 class="sub_tito" >&nbsp; EDITAR CAIXA
    {% if perms.fluxo_de_caixa.add_caixa %}
    <a 
    href="{% url 'caixa'%}">
            Voltar 
    </a>
    {% endif %}
  </h2>

    {% if perms.fluxo_de_caixa.add_caixa %}
    <form class='formulario' method="POST" >
    
   <hr> 
   {% csrf_token %}
   <div> 
      <label for="busca"> Nome</label> <br>
        <input style=" width:200px;" type="text" id="nome_do_caixa" name="nome_do_caixa"
            placeholder="Nome do novo caixa..." value="{{caixa.nome_do_caixa}}" required/>
    </div>
    <div>
      <label> Funcioário responsável</label> <br>
          <select style=" width:230px;" type="select"  name="funcionario" id="funcionario" required/>
              <option value='{{caixa.funcionario.id}}'> {{caixa.funcionario.nome}} </option>
          {% for funcionarios in funcionarios %}
              <option value='{{funcionarios.id}}'> {{funcionarios.nome}} </option>
          {% endfor %}
          </select >
     </div>
          <hr>
          <button  type="submit">Editar</button>

    </form>
    {% endif%}
{% endblock %}

fluxo_de_caixa/templates/lista-venda-usuario.html
{% extends 'base.html'%}
{% block main%}
<br>
    <h2 class="sub_tito" >&nbsp; MINHAS VENDAS
        {% if perms.fluxo_de_caixa.add_venda %}
            <a href="{% url 'atualizar-pedido' %}"> 
            Adicionar 
        {% endif %}
    </a>
    </h2>
    
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'lista-venda-usuario' %}">
    <a id="br_X_mobil" href="#" onclick="document.getElementById
    ('form_mobil').style.display='none';"> X</a>

    <div>
        <label>Número do cliente</label> <br>
        <input style="width:160px" type="search" id="venda" name="venda" placeholder="Número do cliente...">
            <button  type="submit">Buscar</button>
    </div>
    <div>
        <label>Selecionar o dia</label> <br>
        <input style=" padding: 3px;" type="date" id="dia" name="dia">
            <button  type="submit">Filtrar</button>
    </div>
    <div>
        <label>Selecionar o mês</label> <br>
        <select  type="search" id="mes" name="mes" >
                <tr>
                        <option value='{{today.month}}'> __Selecionar__</option>
                        <option value='1'> -Janeiro</option>
                        <option value='2'> -Fevereiro</option>
                        <option value='3'> -Março</option>
                        <option value='4'> -Abril</option>
                        <option value='5'> -Maio</option>
                        <option value='6'> -Junho</option>
                        <option value='7'> -Julho</option>
                        <option value='8'> -Agosto</option>
                        <option value='9'> -Setembro</option>
                        <option value='10'> -Outubro</option>
                        <option value='11'> -Novembro</option>
                        <option value='12'> -Dezembor</option>
                </tr>
                 <br>
        </select>
        <button  type="submit">Filtrar</button>
    </div>
    
    </form>
    
        <a id="mostrar_filtros"
            href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>
        <div class="dashboard">
            <label><b> Total das vendas:</b> R$ {{total_vendas.total}}</label><br>
            <label><b>Total de desconto:</b> R$ {{total_desconto.total}}</label>
        </div>
    <table class='table'>
      <thead>
        <tr>
            <th>Cliente</th>
            <th class="col_table">Data</th>
            <th>Descrição</th>
            <th class="col_table">Desconto</th>
            <th>Valor</th>
            {% if perms.fluxo_de_caixa.add_venda and perms.fluxo_de_caixa.delete_venda%}
            <th >Ação</th>
            {%endif%}
            <th>Estado</th>
            
        </tr>
      </thead>
      <tbody>
        {% for venda in vendas %}
            <tr>
                <td>{{ venda.id }}</td>
                <td class="col_table">{{ venda.data_hora | date:'d/m/y  H:i'}}</td>
                <td >{{ venda.descricao}}</td>
                <td class="col_table">R$ {{ venda.total_desconto }}</td>
                <td>R$ {{ venda.valor }}</td>
                
                {% if perms.fluxo_de_caixa.add_venda and perms.fluxo_de_caixa.delete_venda%}
                <td> 
                 <a href="{% url 'edit-pedido' venda.id %} "> Editar </a> 
                 <a href="{% url 'delete-pedido' venda.id %} ">Excluir</a> 
                </td>
                {%endif%}
                    
                {% if venda.troco < 0  or venda.tipo_de_pagamento_id == None %}
                <td>
                    {% if perms.fluxo_de_caixa.change_venda %}
                         <label> <a Style= 'color: red;' href="{% url 'edit-pedido' venda.id %} "> Pagar </a>  </label>
                        {% else %}
                        <label Style= 'color: red;'> Não Pago </label>
                        {% endif %}
                    {% else %}
                </td>
                <td>
                        <label>Pago </label>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}





fluxo_de_caixa/templates/lista-vendas.html
{% extends 'base.html'%}
{% block main%}
<br>
    <h2 class="sub_tito" >&nbsp; VENDAS REALIZADAS 
        {% if perms.fluxo_de_caixa.add_venda %}
            <a href="{% url 'atualizar-pedido' %}"> 
            Adicionar 
        {% endif %}
    </a>
    </h2>
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'lista-vendas' %}">
        <a id="br_X_mobil" href="#" onclick="document.getElementById
        ('form_mobil').style.display='none';"> X</a>
    <div>    
        <label>Buscar vendas</label> <br>
        <input style="width:160px" type="search" id="id_venda" name="id_venda" placeholder="Número do cliente...">
            <button  type="submit">Buscar</button>
    </div> 
    <div>    
        <label>Buscar por cliente:</label> <br>
        <select style="width:160px" type="search" 
            id="cliente" name="cliente" placeholder="Nome do cliente...">
            <option value="">Selecionar</option>
            {%for c in cliente%}
                <option value="{{c.id}}">{{c.nome}}</option>
            {%endfor%}
        </select>
            <button  type="submit">Buscar</button>
    </div> 
    <div > 
        <label>Selecione o dia</label> <br>
        <input style="padding: 3px; width: 100px;" type="date" id="dia" name="dia">
            <button  type="submit">Filtrar</button>
        </div> 
        <div > 
            <label>Selecione o mês</label> <br>
            <input style="padding: 3px; width: 150px;" type="month" id="mes" name="mes">
            <button  type="submit">Filtrar</button>
        </div> 
    </form>
        <a id= "mostrar_filtros"
        href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>

    <table class='table'>
      <thead>
        <tr>
            <th>Número do Cliente</th>
            <th class="col_table"> Data</th>
            <th>Cliente/CPF</th>
            <th class="col_table">Desconto</th>
            <th>Valor</th>
            {% if perms.fluxo_de_caixa.add_venda and perms.fluxo_de_caixa.delete_venda%}
            <th >Ação</th>
            {%endif%}
            <th >Estado</th>
        </tr>
      </thead>
      <tbody>
        {% for venda in vendas %}
            <tr>
                <td>{{ venda.id }}</td>
                <td class="col_table">{{ venda.data_hora | date:'d/m/y  H:i'}}</td>
                <td >{{ venda.cliente.nome}}- {{ venda.cliente.cpf_cnpj}}</td>
                <td class="col_table">R$ {{ venda.total_desconto }}</td>
                <td>R$ {{ venda.valor }}</td>
                
                    {% if perms.fluxo_de_caixa.add_venda and perms.fluxo_de_caixa.delete_venda%}
                <td>
                    <a href="{% url 'edit-pedido' venda.id %} "> Editar </a>  
            
                    <a href="{% url 'delete-pedido' venda.id %} ">Excluir</a> 
                </td>  
                    {%endif%}
                
                
                {% if venda.troco < 0  or venda.tipo_de_pagamento_id == None %}
                    <td>
                        {% if perms.fluxo_de_caixa.change_venda %}
                            <label> <a Style= 'color: red;' href="{% url 'edit-pedido' venda.id %} "> Pagar </a>  </label>
                        {% else %}
                            <label Style= 'color: red;'> Não Pago </label>
                        {% endif %}
                    </td>
                {% else %}
                    <td>
                        
                        <label>Pago </label>
                    </td>
                {% endif %}
                
            </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}





fluxo_de_caixa/templates/vendas-pagas.html
{% extends 'base.html'%}
{% block main%}
<br>
    <h2 class="sub_tito" >&nbsp; MINHAS VENDAS
        {% if perms.fluxo_de_caixa.add_venda %}
            <a href="{% url 'atualizar-pedido' %}"> 
            Adicionar 
        {% endif %}
    </a>
    </h2>
    
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'vendas_pagas' %}">
    <a id="br_X_mobil" href="#" onclick="document.getElementById
    ('form_mobil').style.display='none';"> X</a>

    <div>
        <label>Número do cliente</label> <br>
        <input style="width:160px" type="search" id="venda" name="venda" placeholder="Número do cliente...">
            <button  type="submit">Buscar</button>
    </div>
    <div>
        <label>Selecionar o dia</label> <br>
        <input style=" padding: 3px;" type="date" id="dia" name="dia">
            <button  type="submit">Filtrar</button>
    </div>
    <div>
        <label>Selecionar o mês</label> <br>
        <select  type="search" id="mes" name="mes" >
                <tr>
                        <option value='{{today.month}}'> __Selecionar__</option>
                        <option value='1'> -Janeiro</option>
                        <option value='2'> -Fevereiro</option>
                        <option value='3'> -Março</option>
                        <option value='4'> -Abril</option>
                        <option value='5'> -Maio</option>
                        <option value='6'> -Junho</option>
                        <option value='7'> -Julho</option>
                        <option value='8'> -Agosto</option>
                        <option value='9'> -Setembro</option>
                        <option value='10'> -Outubro</option>
                        <option value='11'> -Novembro</option>
                        <option value='12'> -Dezembor</option>
                </tr>
                 <br>
        </select>
        <button  type="submit">Filtrar</button>
    </div>
    
    </form>
    
        <a id="mostrar_filtros"
            href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>
        <div class="dashboard">
            <label><b> Total das vendas:</b> R$ {{total_vendas.total}}</label><br>
        </div>
    <table class='table'>
      <thead>
        <tr>
            <th>Cliente</th>
            <th class="col_table">Data</th>
            <th>Descrição</th>
            <th class="col_table">Desconto</th>
            <th>Valor</th>
            <th >Ação</th>
            <th>Estado</th>
            
        </tr>
      </thead>
      <tbody>
        {% for venda in vendas %}
            <tr>
                <td>{{ venda.id }}</td>
                <td class="col_table">{{ venda.data_hora | date:'d/m/y  H:i'}}</td>
                <td >{{ venda.descricao}}</td>
                <td class="col_table">R$ {{ venda.total_desconto }}</td>
                <td>R$ {{ venda.valor }}</td>
                <td> 
                {% if perms.fluxo_de_caixa.add_venda %}
                 <a href="{% url 'edit-pedido' venda.id %} "> Editar </a> 
                {%endif%}

                {% if perms.fluxo_de_caixa.delete_venda %}
                 <a href="{% url 'delete-pedido' venda.id %} ">Excluir</a> </td>
                {%endif%}

                <td>
                    {% if venda.troco < 0  or venda.tipo_de_pagamento_id == None %}
                        {% if perms.fluxo_de_caixa.change_venda %}
                         <label> <a Style= 'color: red;' href="{% url 'edit-pedido' venda.id %} "> Pagar </a>  </label>
                        {% else %}
                        <label Style= 'color: red;'> Não Pago </label>
                        {% endif %}
                    {% else %}
                        <label>Pago </label>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}





fluxo_de_caixa/templates/vendas_update.html
{% extends 'base.html'%}
{% block main%}
<br>
    <div >

        <form class='formulario' action="{% url 'vendas_update' vendas.id%}" method="POST">
            <ul>
                <label class='cadastroTitulo'> Finalizar venda {{data}}</label>
                    {% csrf_token%}
                    {{form.as_p}}
                <button  type="submit">Atualizar</button>
                <p> </p>
                <button  type="submit">Gerar cupom fiscal</button>

            </ul>
        </form>


    </div>
{% endblock %}