financeiro/urls.py
from django.urls import path
from financeiro import views
from .views import ( GastosExtras, GastosExtrasUpdate, Gastos_extras_categoria,
    Gastos_extras_categoriaUpdate,ContasApagar, ContaAreceberUpdate,
    Relarorio_produtos, Relatorio_diario, Relatorio_mensal, Relatorio_anual,
    FiltroGastosExtras, ContasAreceber, ContaApagarUpdate, Pagamentos,Parcelas, Fatura,
    GastosExtrasDashboard
    )


urlpatterns = [
    path('gastos-extras/', GastosExtras.as_view(), name='gastos-extras'),
    path('gastos-extras-delete-confirme/(?P<id>\d+)/', views.gastosExtras_delete, name='gastos_extras_delete'),
    path('gastos_extras_update/<int:id>/', GastosExtrasUpdate.as_view(), name='gastos_extras_update'),
    path('categoria_de_gastos/', Gastos_extras_categoria.as_view(), name='categoria_de_gastos'),
    path('categoria_de_gastosUpdate/<int:id>/', Gastos_extras_categoriaUpdate.as_view(), name='categoria_de_gastosUpdate'),
    path('categoria-de-gastos-delete/(?P<id>\d+)/', views.categoria_de_gastos_delete, name='categoria_de_gastos_delete'),
    path('conta-apagar/', ContasApagar.as_view(), name='conta_apagar'),
    path('pagamento/<int:id>/', Pagamentos.as_view(), name='pagamento'),
    path('parcelas/<int:id>/', Parcelas.as_view(), name='parcelas'),
    path('conta-areceber/', ContasAreceber.as_view(), name='conta_areceber'),
    path('conta-delete-confirme/(?P<id>\d+)/', views.conta_delete, name='conta_delete'),
    path('conta-apagar-delete/(?P<id>\d+)/', views.conta_apagar_delete, name='conta_apagar_delete'),
    path('conta_areceber_update/<int:id>/', ContaAreceberUpdate.as_view(), name='conta_areceber_update'),
    path('conta_apagar_update/<int:id>/', ContaApagarUpdate.as_view(), name='conta_apagar_update'),
    path('relatorio-produtos/', Relarorio_produtos.as_view(), name='relatorio-produtos'),
    path('relatorio-diario/', Relatorio_diario.as_view(), name='relatorio_diario'),
    path('relatorio-mensal/', Relatorio_mensal.as_view(), name='relatorio_mensal'),
    path('relatorio-anual/', Relatorio_anual.as_view(), name='relatorio_anual'),
    path('fatura/', Fatura.as_view(), name='fatura'),
    path('filtro-gastos-extras/', FiltroGastosExtras.as_view(), name='filtro_gastos_extras'),
    path('dashboard/', GastosExtrasDashboard.as_view(), name='dashboard'),
]

home/urls.py
from django.urls import  path
from home import views
from .views import (
    Usuario
)

urlpatterns = [
    #path('', views.home),
    path('', views.home, name='inicio'),
    path('manual/', views.manual, name='manual'),
    path('tela_inicial/', views.TelaInicial, name='tela_inicial'),
    path('usuario/', Usuario.as_view(), name='usuario'),
]

financeiro/models.py
from django.db import models
from django.utils import timezone
#from django.db.models import Sum, F, FloatField #Max ExpressionWrapper ExpressionWrapper, #funções agrega
from django.db.models.signals import post_save
from django.dispatch import receiver
from pessoa.models import Cliente
from fluxo_de_caixa.models import Venda
from django.contrib.auth.models import User
from usuarios.models import Usuarios
from django.db.models import Sum
#import datetime
#from django.utils import timezone

class Relatorios(models.Model):
    descricao=models.CharField(max_length=100, blank=True, verbose_name="Descrição")
    def __str__(self): # METODO CONSTRUTOR
        return self.descricao

class GastosExtrasCategoria(models.Model):
    nome=models.CharField(max_length=30, blank=True, null=True, verbose_name="Nome")
    user = models.CharField(max_length=30, blank=True, null=True, verbose_name="Funcionário")
    usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    def __str__(self): # METODO CONSTRUTOR
        return self.nome

class Gastos_extras(models.Model):
    descricao=models.CharField(max_length=100, blank=True, verbose_name="Descrição")
    valor = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=0)
    data_hora = models.DateTimeField(default=timezone.now)
    gastosExtrasCategoria = models.ForeignKey(GastosExtrasCategoria, blank=True, null=True, on_delete=models.CASCADE)
    arquivo = models.FileField(default=False, blank=True)
    user = models.CharField(max_length=100,null=True, blank=True)
    usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)

    def __str__(self): # METODO CONSTRUTOR
        return self.descricao

class Tipo_de_conta(models.Model):
    nome=models.CharField(max_length=50, blank=True)
    
    def __str__(self): # METODO CONSTRUTOR
       return self.nome

class Contas(models.Model):
    observacao = models.CharField(max_length=100, blank=True, verbose_name="Observação")
    cliente = models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)
    venda = models.ForeignKey(Venda, null=True, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=0)
    valor_com_juros = models.DecimalField(max_digits=9, decimal_places=2, blank=False, null=True, default=0)
    valor_parcela = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=0)
    parcelas_pagas = models.DecimalField(max_digits=9, decimal_places=0, blank=False, default=0)
    parcelas = models.DecimalField(max_digits=9, decimal_places=0, blank=False, default=0)
    saldo_devedor = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=0)
    parcelas_restantes = models.DecimalField(max_digits=9, decimal_places=0, blank=False, default=0)
    juros = models.DecimalField(max_digits=9, decimal_places=2, blank=False, null=True, default=0)
    tipo_de_conta = models.ForeignKey(Tipo_de_conta, on_delete=models.CASCADE)
    data_de_vencimento =models.DateField(default=False, blank=True)
    data_hora = models.DateTimeField(default=timezone.now)
    arquivo = models.FileField(default=False, blank=True)
    user_2 = models.CharField(max_length=100,null=True, blank=True)
    user = models.CharField(max_length=100,null=True, blank=True)
    usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)

    def __str__(self): # METODO CONSTRUTOR
       return str(self.cliente) + ' - ' + str(self.parcelas_restantes)+ ' - ' + str(self.valor)

    def total_contas(self):
#Calculo do valor com juros
        if float(self.juros) > 0 :
            juros= float(self.juros) / 100 #obtendo juros em porcentagem
            total_de_parcela= float(self.parcelas) 
            valor_do_debito= float(self.valor)
            total_valor_com_juros = ((1 + juros)**total_de_parcela - 1) / ((1 + juros)**total_de_parcela * juros)
            total_valor_com_juros = valor_do_debito / total_valor_com_juros * total_de_parcela
            #total_valor_com_juros = valor_do_debito * (1 + juros)**total_de_parcela # Juros composto
            # total_valor_com_juros = float(self.valor) * float(self.juros) / 100 juros simples
            # total_valor_com_juros = total_valor_com_juros + float(self.valor) # juros simples
            self.valor_com_juros = total_valor_com_juros
            Contas.objects.filter(id=self.id).update(valor_com_juros = total_valor_com_juros)
        else:
            valor_com_juros = float(self.valor)
            self.valor_com_juros = valor_com_juros
            Contas.objects.filter(id=self.id).update(valor_com_juros = valor_com_juros)

# Calculo do valor da parcela
        valor_da_parcela = float(self.valor_com_juros) / float(self.parcelas) 
        self.valor_parcela = float(valor_da_parcela)
        Contas.objects.filter(id=self.id).update(valor_parcela = valor_da_parcela)

#pagamento
        pagamento = self.pagamento_set.all().aggregate(total_parcelas = Sum('quantidade_de_parcelas'))
        totalParcelas = pagamento['total_parcelas'] or 0
        self.parcelas_pagas = totalParcelas
        Contas.objects.filter(id=self.id).update(parcelas_pagas = totalParcelas)

# Calcula das parcelas restantes
        parcelasRestantes = float(self.parcelas) - float(totalParcelas)
        self.parcelas_restantes = float(parcelasRestantes)
        Contas.objects.filter(id=self.id).update(parcelas_restantes = parcelasRestantes)

# Calculo do saldo devedor
        saldoDevedor = float(self.valor_com_juros) / float(self.parcelas) * float(self.parcelas_restantes)
        self.saldo_devedor = float(saldoDevedor)
        Contas.objects.filter(id=self.id).update(saldo_devedor = saldoDevedor)

class Pagamento(models.Model):
    observacao = models.CharField(max_length=100, blank=True, verbose_name="Observação")
    quantidade_de_parcelas = models.DecimalField(max_digits=9, decimal_places=0, blank=False, default=0)
    contas = models.ForeignKey(Contas, on_delete=models.CASCADE)
    total_pago = models.DecimalField(max_digits=9, decimal_places=0, blank=False, default=0)
    data_hora = models.DateTimeField(default=timezone.now)
    user = models.CharField(max_length=100,null=True, blank=True)
    usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)

# Valor pago
    def pagamento(self):
        valorPago = float(self.quantidade_de_parcelas) * float(self.contas.valor_parcela)
        self.total_pago = float(valorPago)
        Pagamento.objects.filter(id=self.id).update(total_pago = valorPago)

    def __str__(self): # METODO CONSTRUTOR
       return str(self.quantidade_de_parcelas)  + ' - ' + str(self.contas.parcelas_restantes) + ' - ' + str(self.contas.valor_parcela)

class ParcelasConta(models.Model):
    usuarios = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    user = models.CharField(max_length=100,null=True, blank=True)
    numero_da_parcelas = models.CharField(max_length=100,null=True, blank=True)
    data_de_vencimento =models.DateField(default=False, blank=True)
    contas = models.ForeignKey(Contas, on_delete=models.CASCADE)

@receiver(post_save, sender= Contas)
def update_total_contas(sender, instance, **kwargs):
    instance.total_contas()

@receiver(post_save, sender= Pagamento)
def update_total_conta(sender, instance, **kwargs):
    instance.contas.total_contas()

@receiver(post_save, sender= Pagamento)
def update_pagamento(sender, instance, **kwargs):
    instance.pagamento()








financeiro/templates/financeiro/categoria-de-gastos-delete.html

{% load static%}
<!DOCTYPE html>

<html lang= "pt-br" >

    <head>
        <link rel="stylesheet" href= "{% static 'style/alerta_delete.css'%}">
    </head>
        <body>
            <div class='div_alerta_delete'>
                <form method="POST">
                    <label>ALERTA!</label>
                     <br>
                     <br>
                    <label class='label_mensagem'>Tem certeza disso?</label>
                     <br>
                     <br>
                    {% csrf_token %}
                    <button type="submit">Confirmar</button>
                     <a href="{% url 'categoria_de_gastos_delete' %}"><input  type="button" value='Cancelar'></a>
                </form>
            </div>
        </body>
</html>

financeiro/templates/financeiro/categoria_de_gastosUpdate.html
{% extends 'base.html' %}

{% block main %} 

<br>

    <h2 class="sub_tito" >&nbsp; CATEGORIA DE GASTOS
        <a href="{% url 'categoria_de_gastos'%}"> Adicionar </a>
    </h2>

    <form class='formulario'   method="POST" >
         {% csrf_token %}
        
         <p> EDITAR CATEGORIA</p>
        <hr> 
        <div>
            <label>Nome da categoria</label>
            <input placeholder=" Nome..." type="text" id="nome" name="nome" value="{{categoria.nome}}" required/>
        </div>
             <hr>
            <button type="submit"> Salvar</button>
        
    </form>
     <br>
{% endblock %}

financeiro/templates/financeiro/conta-apagar.html
{% extends 'base.html' %}

{% block main %}
 <br>
    <h2 class="sub_tito" >&nbsp; CONTA A PAGAR
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                Adicionar 
        </a>
    </h2>
    <form id="form_up" class='formulario' style="display: none;" action="{% url 'conta_apagar' %}" method="POST" >
        {% csrf_token %}

        <a id="termo_buttao" href="#" onclick="document.getElementById
        ('form_up').style.display='none';"> X</a>
        <p> NOVA CONTA</p>

       <hr> 
   
        <div>
            <label> Observação</label> <br>
                <input style=" width:220px;"  placeholder=" Observação ou descrição..."
                    type="text" id="observacao" name="observacao" required/>
        </div>
        <div>
            <label> Valor</label> <br>
                <input style=" width:120px;"  placeholder="R$ 0,00" type="text" data-js="money"
                    id="valor" name="valor" required/>
        </div>
        <div>  
             <label> Parcelas</label> <br>
                <input style=" width:120px;" value='1' data-js="numero"
                    type="text" id="parcelas" name="parcelas" required/>
        </div>
        <div>  
            <label> Juros</label> <br>
               <input style=" width:120px;" placeholder=" 0,00%"
                   type="number" step=".01" lang="nb" id="juros" name="juros">
       </div>
        <div>
                <input type="hidden" value='2' name="tipo_de_conta_id">

            <label> Primeira parcela</label> <br>
                <input style=" width:150px; padding:3px;"  placeholder=" Data de vencimento:"
                    type="date" id="data_de_vencimento" name="data_de_vencimento" required/>
        </div>
               
            <hr>
            <button type="submit"> Salvar</button>
    </form>
        <br>

<!-- Formulário de filtros -->

    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'conta_apagar' %}">
        <a id="br_X_mobil" href="#" onclick="document.getElementById
        ('form_mobil').style.display='none';"> X</a>
    
    <div>
        <label>Situação do débito</label><br>
         <select  type="search" id="estado_da_conta" name="estado_da_conta" >
           <tr >
                <option value=''> __Selecionar__</option>
                <option value=''> -Contas ativas</option>
                <option value='0'> -Contas pagas</option>
            </tr>
        </select>
            <button type="submit">Filtrar</button>
    </div>
    
    <div>
        <label>Filtrar por periodo</label> <br>
        <select type="search" id="data_vencimento" name="data_vencimento" >
            <tr >
                <option value=''> __Selecionar__</option>
                <option value='3'> -Hoje__</option>
                <option value='2'> -Últimos 5 dias</option>
                <option value='1'> -Esse mês</option>
             </tr>
        </select>
            <button  type="submit">Filtrar</button>
    </div>
    </form>
        <a id="mostrar_filtros"
            href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>    
    <table class="table">
     <thead>
        <tr>
            <th >Observação</th>
            <th >Valor</th>
            <th class="col_table" >Juros</th>
            <th class="col_table" >Valor com juros</th>
            <th  class="col_table">Saldo devedor</th>
            <th class="col_table">Total de parcelas</th>
            <th class="col_table" >Parcelas pagas</th>
            <th class="col_table" >Parcelas restantes</th>
            <th class="col_table">Valor da parcela</th>
            <th >Primeira parcela</th>
            <th >Açao</th>
            <th >Pagar</th>
            

        </tr>
    </thead>
        <tbody>
            {%for conta in conta %}
                <tr>
                    <td >{{ conta.observacao}}</td>
                    <td>R$ {{ conta.valor }}</td>
                    <td class="col_table">{{ conta.juros}} %</td>
                    <td class="col_table">R$ {{ conta.valor_com_juros}}</td>
                    <td class="col_table">R$ {{ conta.saldo_devedor }}</td>
                    <td class="col_table"> {{ conta.parcelas }}</td>
                    <td class="col_table">{{ conta.parcelas_pagas }}</td>
                    <td class="col_table">{{ conta.parcelas_restantes }}</td>
                    <td class="col_table">R$ {{ conta.valor_parcela }}</td>
                    <td >{{ conta.data_de_vencimento | date:'d/m/y' }}</td>
                    <td> 
                        {% if perms.financeiro.change_contas %}
                                <a href="{% url 'conta_apagar_update' conta.id %}">Editar</a> 
                            {%endif%}

                            {% if perms.financeiro.delete_contas %}
                                <a href="{% url 'conta_apagar_delete' conta.id %}">Excluir</a> 
                        {%endif%}
                    </td>
                    <td>
                    {%if conta.parcelas_restantes == 0%}
                        {% if perms.financeiro.add_pagamento %}
                        <a href="{% url 'pagamento' conta.id %}">Pago</a> 
                        {%endif%}

                    {%else%}

                        {% if perms.financeiro.add_pagamento %}
                        <a href="{% url 'parcelas' conta.id %}">Parcelas</a> 
                        {%endif%}

                    {%endif%}
                    </td>
                    

                </tr>
            {%endfor%}
        </tbody>
    </table>
{% endblock %}
<!-- <td> <a href="{% url 'GastosExtras_update_cbv' gastos_extras.id %}">Editar</a> </td>
                    <td> <a href="{% url 'gastos_extras_delete' gastos_extras.id %}">Excluir</a> </td>  -->


financeiro/templates/financeiro/conta-areceber.html
{% extends 'base.html' %}
{% block main %}
{% load static%}
<br>
    <h2 class="sub_tito" >&nbsp; CONTA A RECEBER <br>
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                ADICIONA 
        </a>
        <div>
            <label class="sub_menu"> 
                <img id="img_menu" src="{% static 'img/cliente.png' %}" width="500px" all=" ">
                <a href="{% url 'novo-cliente' %}">CLIENTES</a>
            </label>
        </div>
    </h2>
    <form id="form_up" class='formulario' style="display: none;" action="{% url 'conta_areceber' %}" method="POST" >
        {% csrf_token %}
        
        <a id="termo_buttao" href="#" onclick="document.getElementById
        ('form_up').style.display='none';"> X</a>
        <p> NOVA CONTA</p>

       <hr> 
        <div>
            <label> Observação</label><br>
                <input  placeholder=" Observação ou descrição..."
                    type="text" id="observacao" name="observacao" />
        </div>
        <div>  
            <label> Cliente</label><br>
                <select  type="search" id="cliente_id" name="cliente_id" required/>

                        <tr>
                                <option value=''> __Selecionar __</option>
                            {% for cliente in cliente %}
                                <option value='{{cliente.id}}'> {{cliente.nome}}</option>
                            {% endfor %}
                        </tr>
                </select>
                <a class="link_add" href="{% url 'novo-cliente' %}">+</a>
        </div>   
        <div>
            <label> Venda</label><br>
                <select  type="search" id="venda_id" name="venda_id" >
                    <tr>
                            <option value=''> __Selecionar__</option>
                        {% for vendas in venda %}
                            <option value='{{vendas.id}}'> {{vendas}}</option>
                        {% endfor %}
                    </tr>
                </select>

        </div>
        <div>
            <label> Valor</label><br>
                <input  placeholder="R$ 0,00"  type="text" data-js="money" step=".01" lang="nb"
                    id="valor" name="valor" required/>
        </div>
    
        <div>
             <label> Parcelas</label><br>
                <input value='1'  data-js="numero"
                    type="text" id="parcelas" name="parcelas" required/>
        </div>
        <div>  
            <label> Juros</label> <br>
               <input style=" width:120px;" placeholder=" 0,00 %"
               type="number" step=".01" lang="nb" id="juros" name="juros" >
        </div> 
       
                <input type="hidden" value='1' name="tipo_de_conta_id">
       
        <div> 
            <label> Primeira parcela</label> <br>
                <input style=" width:150px; padding: 3px;"  placeholder=" Data de vencimento:"
                    type="date" id="data_de_vencimento" name="data_de_vencimento" required/>
        
        </div>
        <hr>

            <button type="submit"> salvar</button>
    </form>
        <br>

<!-- Formulário de filtros -->
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'conta_areceber' %}">
        <a id="br_X_mobil" href="#" onclick="document.getElementById
        ('form_mobil').style.display='none';"> X</a>
    
    <div id="div_busca_filtro";>
        <label> Buscar cliente:</label><br>
        <select style="width:110px"; type="text" id="nome_cliente" name="nome_cliente" >
            <option value=''> Selecionar</option>
            {%for c in cliente%}
            <option value='{{c.cliente.id}}'> {{c.cliente.nome}} - {{c.cliente.cpf_cnpj}}</option>
            {%endfor%}
        </select>
        <button style="width:60px"; type="submit">Buscar</button>
    </div> 
    <div id="div_busca_filtro";>
        <label> Cpf ou Cnpj / Situação do débito</label><br>
        <input style="width:150px"; type="search" id="client" name="client" 
            data-js="cpf" placeholder="000.00.000-00" >
        
        <select style="width:110px"; type="text" id="estado_da_conta" name="estado_da_conta" >
                <option value=''> Selecionar</option>
                <option value='1'> -Contas ativas </option>
                <option value='2'> -Contas pagas </option>
        </select>
        <button style="width:50px"; type="submit">Filtrar</button>
    </div> 
    <div id="div_busca_filtro";> 
        <label>Filtra por periodo  </label> <br>
        <input  style="width:120px; padding: 3px;" type="date" id="dia" name="dia" > até
        <input  style="width:120px; padding: 3px;" type="date" id="dia2" name="dia2" >
        <button style="width:50px;" type="submit">Filtrar</button>
    </div> 
    </form>
        <a id="mostrar_filtros"
            href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>
    <table class="table">
     <thead>
        <tr>
            <th >Cliente</th>
            <th class="col_table">Observação</th>
            <th >Valor</th>
            <th class="col_table" >Juros</th>
            <th class="col_table">Valor com juros</th>
            <th class="col_table">ID da venda</th>
            <th class="col_table">Saldo devedor</th>
            <th class="col_table">Total de parcelas</th>
            <th class="col_table" >Parcelas pagas</th>
            <th class="col_table" >Parcelas restantes</th>
            <th class="col_table" >Valor da parcela</th>
            <th >Primeira parcela</th>
            <th>Ação</th>
            <th>Pagar</th>
        </tr>
    </thead>
        <tbody>
            {%for conta in conta %}
                <tr>
                    <td>{{ conta.cliente.nome}}</td>
                    <td class="col_table">{{ conta.observacao}}</td>
                    <td >R$ {{ conta.valor }}</td>
                    <td class="col_table"> {{ conta.juros}} %</td>
                    <td class="col_table">R$ {{ conta.valor_com_juros}}</td>
                    <td class="col_table">{{ conta.venda.id}}</td>
                    <td class="col_table">R$ {{ conta.saldo_devedor }}</td>
                    <td class="col_table">{{ conta.parcelas }}</td>
                    <td class="col_table">{{ conta.parcelas_pagas }}</td>
                    <td class="col_table">{{ conta.parcelas_restantes }}</td>
                    <td class="col_table">R$ {{ conta.valor_parcela }}</td>
                    <td>{{ conta.data_de_vencimento | date:'d/m/y' }}</td>
                    <td>
                        {% if perms.financeiro.change_contas %}
                            <a href="{% url 'conta_areceber_update' conta.id %}">Editar</a> 
                        {%endif%}

                        {% if perms.financeiro.delete_contas %}
                            <a href="{% url 'conta_delete' conta.id %}">Excluir</a> 
                        {%endif%}
                    </td>
                    <td>
                    {%if conta.parcelas_restantes == 0%}
                        {% if perms.financeiro.add_pagamento %}
                        <a href="{% url 'pagamento' conta.id %}">Pago</a> 
                        {%endif%}

                    {%else%}

                        {% if perms.financeiro.add_pagamento %}
                        <a href="{% url 'parcelas' conta.id %}">Parcelas</a> 
                        {%endif%}

                    {%endif%}
    
                    </td>
            {%endfor%}
        </tbody>
    </table>
{% endblock %}

financeiro/templates/financeiro/gastos-extras-delete-confirme.html

{% load static%}
<!DOCTYPE html>

<html lang= "pt-br" >

    <head>
        <link rel="stylesheet" href= "{% static 'style/alerta_delete.css'%}">
    </head>
        <body>
            <div class='div_alerta_delete'>
                <form method="POST">
                    <label>ALERTA!</label>
                     <br>
                     <br>
                    <label class='label_mensagem'>Tem certeza disso?</label>
                     <br>
                     <br>
                    {% csrf_token %}
                    <button type="submit">Confirmar</button>
                     <a href="{% url 'gastos-extras' %}"><input  type="button" value='Cancelar'></a>
                </form>
            </div>
        </body>
</html>

financeiro/templates/financeiro/gastos-extras.html
{% extends 'base.html' %}
{% block main %} 
{% load static%}
    <br>
    <h2 class="sub_tito" >&nbsp; CONTROLE DE GASTOS
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                Adicionar 
        </a>
        <div > 
            <label class="sub_menu"> 
                <img id="img_menu" src="{% static 'img/relatorio.png' %}" >
                <a href="{% url 'dashboard' %}">DASHBOARD</a>
            </label>
        </div>
    </h2>
    <form id="form_up" class='formulario' style="display: none;" action="{% url 'gastos-extras' %}" method="POST" >
         {% csrf_token %}
         <a id="termo_buttao" href="#" onclick="document.getElementById
         ('form_up').style.display='none';"> X</a>
        <hr> 
    <div> 
        <label>Descrição*</label><br>
            <input placeholder=" Descrição..." type="text" id="descricao" name="descricao" required/>
    </div>
    <div> 
        <label>Categoria de gastos</label><br>
            <select style="width:180px;" type="search" id="categoria" name="categoria">
                <option value="">Selecionar</option>
                {%for categoria in categoria_de_gastos %}
                <option value="{{categoria.id}}">{{categoria}}</option>
                {%endfor%}
            </select> 
            <a class="link_add" href="{% url 'categoria_de_gastos' %}">+</a>
    </div>
    <div>
        <label>Valor*</label><br>
            <input placeholder="R$ 0,00" type="text" data-js="money" name="valor" required/>
    </div>
             <hr>
            <button type="submit"> Salvar</button>
    </form>

<!-- formulário de filtro -->
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'filtro_gastos_extras' %}">
        <a id="br_X_mobil" href="#" onclick="document.getElementById
        ('form_mobil').style.display='none';"> X</a>

    <div>
        <label> Filtrar por periodo/categoria</label> <br>
        <input style="width:150px;" type="month" id="mes" name="mes"/>
        <tr>
        <select style="width:80px;" type="search" id="categoria" name="categoria">
            <option value="">categora</option>
            {%for categoria in categoria_de_gastos %}
            <option value="{{categoria.id}}">{{categoria}}</option>
            {%endfor%}
        </select> 

        <button style="width:50px;" type="submit">Filtrar</button>
    </div>
    
    </form>
        <a id="mostrar_filtros"
            href="#" onclick="document.getElementById('form_mobil').style.display='block';">
            Mostrar filtros 
        </a>
    {% if gastos_extr.total > 0 %}
        <div class="dashboard">
            <label><b>&nbsp; Total:</b> R$ {{gastos_extr.total}}</label><br>
        </div>
    {%endif%}
    <table class="table">
     <thead>
        <tr>
          <th >Descrição</th>
          <th >Valor</th>
          <th >Categoria</th>
          <th>Data</th>
          <th >Ação</th>
        </tr>
    </thead>
        <tbody>
            {%for gastos_extras in gastos_extras %}
                <tr>
                    <td>{{ gastos_extras.descricao }}</td>
                    <td>R$ {{ gastos_extras.valor  | floatformat:2}}</td>
                    <td>{{ gastos_extras.gastosExtrasCategoria.nome }}</td>
                    <td>{{ gastos_extras.data_hora | date:'d/m/y  H:i'}}</td>

                    {% if perms.financeiro.change_gastos_extras %}
                    <td>
                        <a href="{% url 'gastos_extras_update' gastos_extras.id %}">Editar</a>
                    {% endif%}
                    {% if perms.financeiro.delete_gastos_extras %}
                        <a href="{% url 'gastos_extras_delete' gastos_extras.id %}">Excluir</a>
                    </td>
                    {% endif%}
                    
                </tr>
            {%endfor%}
        </tbody>
    </table>



{% endblock %}