home/urls.py
from django.urls import  path
from home import views
from .views import (
    Usuario
)

urlpatterns = [
    #path('', views.home),
    path('', views.home, name='inicio'),
    path('manual/', views.manual, name='manual'),
    path('tela_inicial/', views.TelaInicial, name='tela_inicial'),
    path('usuario/', Usuario.as_view(), name='usuario'),
]

produto/urls.py
from django.urls import path
from produto import views
from .views import (
    NovoProduto, ListaProdutos, Categoria_de_produto, FiltroPorCategoria,
    Entrada_Mercadoria , ProdutoUpdate, CategoriaUpdate, EntradaMercadoriaUpdate,
    FiltrarEntadaPorCategoria, NovaPromocao, PromocaoUpdate, ValidadeProdutos,
)
urlpatterns = [
    #path('', ListaVendas.as_view(), name='lista-vendas'),
    path('listar-produto/', ListaProdutos.as_view(), name='listar-produto'),
    path('categoria/', Categoria_de_produto.as_view(), name='categoria'),
    path('entrada-mercadoria/', Entrada_Mercadoria.as_view(), name='entrada-mercadoria'),
    path('validade-produtos/', ValidadeProdutos.as_view(), name='validade-produtos'),
    path('produto/', NovoProduto.as_view(), name="produto"),
    path('promocao/', NovaPromocao.as_view(), name="promocao"),
    path('promocao-update/(?P<id>\d+)/', PromocaoUpdate.as_view(), name='promocao-update'),
    path('delete-promocao-confirm/(?P<id>\d+)/', views.promocao_delete, name='promocao_delete'),
    path('produto_update/(?P<id>\d+)/', ProdutoUpdate.as_view(), name='produto_update'),
    path('delete-produto-confirm/(?P<id>\d+)/', views.produto_delete, name='produto_delete'),
    path('categoria_update/<int:id>/', CategoriaUpdate.as_view(), name='categoria_update'),
    path('delete-categoria-confirm/(?P<id>\d+)/', views.categoria_delete, name='categoria_delete'),
    path('entrada_mercadoria_update/(?P<id>\d+)/', EntradaMercadoriaUpdate.as_view(), name='entrada_mercadoria_update'),
    path('entradaMercadoria-delete-confirme/(?P<id>\d+)/', views.entradaMercadoria_delete, name='entradaMercadoria_delete'),
    path('filtro-categoria/', FiltroPorCategoria.as_view(), name='filtro-categoria'),
    path('filtro-categoria-entrada-mercadoria/', FiltrarEntadaPorCategoria.as_view(), name='filtro-categoria-entrada-mercadoria'),
]

produto/models.py
from django.db import models
from django.utils import timezone
#from django.contrib.auth.models import User
from django.db.models import  F,Sum,DecimalField # Max ExpressionWrapper FloatField DecimalField Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
#from django.core.urlresolvers import reverse
#import matplotlib.pyplot as plt
#from vendas.models import ItemDoPedido
#from django.contrib.auth.models import User
from pessoa.models import Fornecedor
from django.contrib.auth.models import User
from usuarios.models import Usuarios
#from datetime import tade
#import math

class Categoria (models.Model):
    nome = models.CharField(max_length=50, blank=True)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)


    def __str__(self): # METODO CONSTRUTOR
       return self.nome

class Promocao(models.Model):
    descricao = models.CharField(max_length=50,  null = True, verbose_name="Descrição")
    quantidade_promocional = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    desconto = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    data_inicio = models.DateField(blank=True, null=True)
    data_termino = models.DateField(blank=True, null=True)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)

    def __str__(self): # METODO CONSTRUTOR
        return str(self.descricao)+ ' , ' + str(self.data_inicio)+ ' Até ' + str(self.data_termino)

class Produto (models.Model):
    nome = models.CharField(max_length=30,  blank=True)
    categoria = models.ForeignKey(
        Categoria, verbose_name='Categoria', on_delete=models.CASCADE, default=1)
    promocao = models.ForeignKey(
        Promocao, null = True, on_delete=models.CASCADE, verbose_name="Promoção")
    codigo = models.CharField(max_length=13, blank=False)
    percentagem_de_lucro = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    valor_venal = models.DecimalField(max_digits=9, decimal_places= 2, default=0)
    valor_compra = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=0)
    entrada = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    saida = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    estoque = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    data_hora = models.DateTimeField(default=timezone.now)
    imagem = models.ImageField( blank=True)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)


    def __str__(self): # METODO CONSTRUTOR
        return str(self.nome)+ ' - ' +str(self.id)

    def atualizar_estoque(self):
        # entrada de mercadoria
        entrada_de_mercadoria = self.entradamercadoria_set.all().aggregate(
           total_entrada = Sum(F('quantidade'), output_Field=DecimalField()))
        total_entrada = entrada_de_mercadoria['total_entrada'] or 0
        self.entrada = total_entrada
        Produto.objects.filter(id=self.id).update(entrada = total_entrada)

        # somando o total de item 
        item_do_pedido = self.itemdopedido_set.all().aggregate(
            total_item = Sum(F('quantidade_de_itens'), output_Field=DecimalField()))
        total_item = item_do_pedido['total_item'] or 0
        self.saida = total_item
        Produto.objects.filter(id=self.id).update(saida = total_item)

        self.estoque= self.entrada - self.saida
        Produto.objects.filter(id=self.id).update(estoque = self.estoque)

        percentagem_de_lucro= float(self.percentagem_de_lucro)
        if percentagem_de_lucro > 0:
            valor_produto= float(
                self.valor_compra) * float(
                    self.percentagem_de_lucro) / 100 + float(self.valor_compra)
            self.valor_venal = valor_produto
            Produto.objects.filter(id=self.id).update(valor_venal = valor_produto)
        if percentagem_de_lucro <= 0:
            lucro= float(self.valor_venal) - float(self.valor_compra)
            lucro_estimado= lucro / float(self.valor_compra) * 100 
            self.percentagem_de_lucro = lucro_estimado
            Produto.objects.filter(id=self.id).update(percentagem_de_lucro = lucro_estimado)

class EntradaMercadoria(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    fornecedor = models.ForeignKey(Fornecedor, null=True, on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=9, decimal_places=2, blank=False, default=1)
    data_hora = models.DateTimeField(default=timezone.now)
    validade_produto = models.DateField(blank=True, null=True)
    user = models.CharField(max_length=100, blank=True, null=True)
    usuarios = models.ForeignKey(Usuarios, null=True, on_delete=models.CASCADE)

    def __str__(self):# METODO CONSTRUTOR
        return str(self.produto.nome)+ ' - ' + str(self.produto.estoque)

@receiver(post_save, sender=Produto)
def update_atualizar_estoque(sender, instance, **kwargs):
    instance.atualizar_estoque()

@receiver(post_save, sender=EntradaMercadoria)
def update_entrada_mercadoria(sender, instance, **kwargs):
    instance.produto.atualizar_estoque()

produto/views.py
from django.shortcuts import render , redirect
from .models import Produto, Categoria, EntradaMercadoria , Fornecedor, Promocao
from django.views import View
from datetime import date, timedelta
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from usuarios.permitir_autorizar import autenticar_usuario, autorizarcao_de_reistro

class NovoProduto(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user.has_perm('produto.add_produto')
        if user == False:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros

        today = date.today()
        produto=Produto.objects.filter(usuarios_id = usuario_cliente).order_by('-id')
        categoria = Categoria.objects.filter(usuarios_id = usuario_cliente).order_by('-id')
        promocao = Promocao.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
        return render(request, 'produto/produto.html', {
            'categoria': categoria, 'produto': produto,
            'today': today, 'promocao':promocao
            })
     
    def post(self, request): 
        data = {}
        today = date.today()
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros

        produto= Produto.objects.filter(usuarios_id= usuario_cliente, codigo= request.POST['codigo']) or 0
        if produto != 0:
            data['mensagen_de_erro'] = 'Esse produto já existe!'
            data['produto']  = Produto.objects.filter(usuarios_id= usuario_cliente) 
            data['categoria'] =Categoria.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            data['promocao'] = Promocao.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            return render(
                request, 'produto/produto.html', data)
        else:
            produto = Produto.objects.create(
                nome = request.POST['nome'],
                categoria_id = request.POST['categoria_id'],
                codigo = request.POST['codigo'],
                percentagem_de_lucro = request.POST['percentagem_de_lucro'].replace(',', '.') or 0,
                valor_venal = request.POST['valor_venal'].replace('.','').replace(',','.').replace('R$\xa0','').replace('R$','') or 0,
                promocao_id = request.POST['promocao' ],
                valor_compra = request.POST['valor_compra'].replace('.','').replace(',','.').replace('R$\xa0','').replace('R$',''),
                user = user_logado, usuarios_id = usuario_cliente
                )

            data['produto'] = produto
            data['produto']  = Produto.objects.filter(usuarios_id= usuario_cliente).order_by('-id') 
            data['categoria'] =Categoria.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            data['promocao'] = Promocao.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            data['today'] = today
            return render(
                request, 'produto/produto.html', data)

@login_required()
def produto_delete(request, id):
    user = request.user.has_perm('produto.delete_produto')
    if user == False:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    user_logado = request.user.id
    usuario_cliente = autenticar_usuario(user_logado)
    autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
    if autorizarcao_de_reistros:
        return autorizarcao_de_reistros

    data  = {}
    produto = Produto.objects.get(id=id)
    usuario_adm= produto.usuarios.id
    if usuario_adm == usuario_cliente:
        if request.method == 'POST':
            produto.delete()
            return redirect('produto')
        else:
            return render(request, 'produto/delete-produto-confirm.html',data)
    else:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
class ProdutoUpdate(LoginRequiredMixin, View):
    def get(self, request, id):
        data = {}
        user = request.user.has_perm('produto.add_produto')
        if user == False:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros
           
        produto = Produto.objects.get(id=id)
        usuario_adm= produto.usuarios.id
        if usuario_adm == usuario_cliente: 

            data['produto']  = Produto.objects.get(id= id)
            data['categoria'] =Categoria.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            data['promocao'] = Promocao.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
            return render(request, 'produto/produto_update.html',data)
        else:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

    def post(self, request, id):
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros

        data = {}
        produto = Produto.objects.get(id=id)
        usuario_adm= produto.usuarios.id
        codigo_produto_autal= produto.codigo
        novo_codigo_produto= request.POST['codigo']
        produto_id= Produto.objects.filter(usuarios_id= usuario_cliente, codigo= request.POST['codigo']) or 0
        if codigo_produto_autal != novo_codigo_produto: 
            if produto_id != 0:
                data['mensagen_de_erro'] = 'Esse produto já existe!'
                data['produto']  = Produto.objects.filter(usuarios_id= usuario_cliente) 
                data['categoria'] =Categoria.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
                data['promocao'] = Promocao.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
                return render(
                    request, 'produto/produto_update.html', data)
        if usuario_adm == usuario_cliente: 
            produto.id = id
            produto.nome = request.POST['nome']
            produto.categoria_id = request.POST['categoria_id']
            produto.codigo = request.POST['codigo']
            if request.POST['percentagem_de_lucro']:
                produto.percentagem_de_lucro = request.POST['percentagem_de_lucro'].replace(',', '.')
            produto.valor_venal = request.POST['valor_venal'].replace('.','').replace(',','.').replace('R$\xa0','').replace('R$','') or 0
            produto.promocao_id = request.POST['promocao' ]
            produto.valor_compra = request.POST['valor_compra'].replace('.','').replace(',','.').replace('R$\xa0','').replace('R$','')
            produto.user = user_logado
            produto.save()
            return redirect('produto')

        else:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

class ListaProdutos(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user.has_perm('produto.view_produto')
        if user == False:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros

        produto=Produto.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
        produt= request.GET.get('produt',None)
        if produt:
            produto=Produto.objects.filter(codigo__icontains=produt, usuarios_id= usuario_cliente) 
        return render(request, 'produto/listar-produto.html', {'produto': produto})

class FiltroPorCategoria(LoginRequiredMixin, View): 
    def get(self, request):
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)
        autorizarcao_de_reistros = autorizarcao_de_reistro(usuario_cliente)
        if autorizarcao_de_reistros:
            return autorizarcao_de_reistros

        categoria = Categoria.objects.filter(usuarios_id= usuario_cliente).order_by('-id')
        produto = Produto.objects.filter(usuarios_id= usuario_cliente).order_by
        busca= request.GET.get('produt',None)
        busca_categoria= request.GET.get('busca_categoria',None)
        if busca:
            produto=Produto.objects.filter(codigo__iexact=busca, usuarios_id= usuario_cliente) 
        if busca_categoria:
            produto = Produto.objects.filter(categoria__id= busca_categoria, usuarios_id= usuario_cliente).order_by('-id') 
        return render(
            request, 'produto/produto.html', {
                'produto': produto, 'categoria': categoria
                })

class NovaPromocao (LoginRequiredMixin, View):
    def get(self, request):
        user = request.user.has_perm('produto.add_promocao')
        if user == False:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
        user_logado = request.user.id
        usuario_cliente = autenticar_usuario(user_logado)

produto/templates/produto/categoria.html
{% extends 'base.html' %}

{% block main %} 

<br>

    <h2 class="sub_tito" >&nbsp; CATEGORIA
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                Adicionar 
        </a>
    </h2>

    <form id="form_up" class='formulario' style="display: none;" action="{% url 'categoria' %}" method="POST" >
         {% csrf_token %}
         <a id="termo_buttao" href="#" onclick="document.getElementById
         ('form_up').style.display='none';"> X</a>
         <p> NOVA CATEGORIA</p>

        <hr> 
        <div>
            <label>Nome da categoria</label>
            <input placeholder=" Nome..." type="text" id="nome" name="nome" required/>
        </div>
             <hr>
            <button type="submit"> Salvar</button>
        
    </form>
     <br>
    <table class="table">
     <thead>
        <tr>
          <th >Categoria</th>
          {% if perms.produto.change_categoria %}
            <th >Alterar</th>
          {% endif %}

        </tr>
    </thead>
        <tbody>
            {%for categoria in categoria %}
                <tr>
                    <td style="text-align: left;"> {{ categoria.nome }}</td>

                {% if perms.produto.change_categoria %}
                    <td> <a href="{% url 'categoria_update' categoria.id %}">Editar</a> 
                {% endif %}

                {% if perms.produto.delete_categoria %}
                    <a href="{% url 'categoria_delete' categoria.id %}">Excluir</a> </td>
                {% endif %}
                </tr>
            {%endfor%}
        </tbody>
    </table> 

{% endblock %}





produto/templates/produto/categoria_update.html
{% extends 'base.html' %}

{% block main %}

<br>
    <h2 class="sub_tito" >&nbsp; CATEGORIA <a href="{% url 'categoria' %}">Cancelar</a></h2>
    <form class='formulario' method="POST" >
         {% csrf_token %}
         <p> EDITAR CATEGORIA</p>
         <hr>
    <div>
            <label> Nome</label><br>
            <input style=" width:310px;"  placeholder=" nome..." value="{{categoria.nome}}"
                 type="text" id="nome" name="nome" required/>
    </div>
            <hr>
            <button type="submit"> Editar</button>
    </form>
     <br>
{% endblock %}





produto/templates/produto/delete-categoria-confirm.html

{% load static%}
<!DOCTYPE html>

<html lang= "pt-br" >

    <head>
        <link rel="stylesheet" href= "{% static 'Style/alerta_delete.css'%}">
    </head>
        <body>
            <div class='div_alerta_delete'>
                <form  method="POST">
                    <label>ALERTA!</label>
                     <br>
                     <br>
                    <label class='label_mensagem'>Tem certeza disso?</label>
                     <br>
                     <br>
                    {% csrf_token %}
                    <button type="submit">Confirmar</button>
                     <a href="{% url 'categoria' %}"><input  type="button" value='Cancelar'></a>
                </form>
            </div>
        </body>
</html>

produto/templates/produto/edit-produto.html
<form  method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

produto/templates/produto/entrada-mercadoria.html
{% extends 'base.html' %}
{% block main %}
{% load static%}
    <br>
    <h2 class="sub_tito" >&nbsp; ENTRADA DE MERCADORIA
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                Adicionar 
        </a> 
        <div > 
            <label class="sub_menu"> 
                <img id="img_menu" src="{% static 'img/frente_de_caixa.png' %}" width="500px" all=" ">
                <a href="{% url 'atualizar-pedido' %}">FRENTE DE CAIXA </a>
            </label> 
            <label class="sub_menu"> 
                <img id="img_menu" src="{% static 'img/produto.png' %}" >
                <a href="{% url 'produto' %}">PRODUTOS</a>
            </label>

            <label class="sub_menu"> 
                <img id="img_menu" src="{% static 'img/saida.png' %}" >
                <a href="{% url 'saida_mercadoria' %}">SAIDA</a>
            </label>
        </div>
    </h2>
    <form id="form_up" class='formulario' style="display: none;" method="POST" action="{% url 'entrada-mercadoria' %}" >
        {% csrf_token %}

        <a id="termo_buttao" href="#" onclick="document.getElementById
        ('form_up').style.display='none';"> X</a>
        <p> NOVA ENTRADA</p>

        <hr> 
        <div> 
            <label> Produto</label> <br>
            <select style=" width:200px;" type="search" id="produto" name="produto" required/>
                <tr>
                    <option value=''> __Selecionar__</option>
                    {% for produto in produto %}
                        <option value='{{produto.id}}'> {{produto}}</option>
                    {% endfor %}
                </tr>
            </select>
                <a  href="{% url 'produto' %}">+</a>
        </div>
        <div>
            <label> Fornecedor</label> <br>
            <select style=" width:200px;" type="search" id="fornecedor" name="fornecedor">
                <tr>
                    <option value=''> __Selecionar__</option>
                    {% for fornecedor in fornecedor %}
                        <option value='{{fornecedor.id}}'> {{fornecedor}}</option>
                    {% endfor %}
                </tr>
            </select>
                <a href="{% url 'novo-fornecedor' %}">+</a>
        </div>
        <div>
            <label> Quantidade</label> <br>
            <input style=" width:200px;"  placeholder=" Quantidade..."
                type="text" id="quantidade" name="quantidade"  required/>
        </div>
        <div>
            <label> Validade do produto</label> <br>
            <input style=" width:150px; padding:3px;"
                type="date" id="validade_produto" name="validade_produto" >
        </div>
            <hr>
            <button type="submit"> Salvar</button>
    </form>
    <br>
<!-- formulário de filtro -->
    <form id="form_mobil" class='campo_de_busca' method="GET" action="{% url 'filtro-categoria-entrada-mercadoria' %}">
        <a id="br_X_mobil" href="#" onclick="document.getElementById
    ('form_mobil').style.display='none';"> X</a>
        
        <div>
            <label>Buscar produto</label> <br>
            <input  type="search" id="produt" name="produt" placeholder="Digite o código">
            <button  type="submit">Buscar</button>
        </div>
        <div>
            <label>Selecionar o mês e o ano</label> <br>
            <input  type="month" id="mes" name="mes" />
                <button  type="submit">Filtrar</button>
        </div>
    </form>
    
    <a id="mostrar_filtros"
    href="#" onclick="document.getElementById('form_mobil').style.display='block';">
    Mostrar filtros 
    </a>

<!--tabela de entrada de mercadoria  -->
    <table class="table">
     <thead>
        <tr>
            <th >Nome</th>
            <th >Código</th>
            <th class="col_table"> Fornecedor </th>
            <th class="col_table">CNPJ do fornecedor</th>
            <th >Quantidade</th>
            <th class="col_table">Data</th>
            <th class="col_table"> Validade</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        {% for entrada in entrada_Mercadoria %}
        <tr>
            <td>{{ entrada.produto.nome}}</td>
            <td>{{ entrada.produto.id}}</td>
            <td class="col_table">{{ entrada.fornecedor.nome_fantazia}}</td>
            <td class="col_table">{{ entrada.fornecedor.cnpj}}</td>
            <td>{{ entrada.quantidade}}</td>
            <td class="col_table">{{ entrada.data_hora.date | date:'d/m/y'}}</td>
            <td class="col_table">{{ entrada.validade_produto | date:'d/m/y'}}</td>

            {% if perms.produto.change_entradamercadoria %}
                <td> <a href="{% url 'entrada_mercadoria_update' entrada.id %}">Editar</a> 
            {%endif%}

            {% if perms.produto.delete_entradamercadoria %}
                 <a href="{% url 'entradaMercadoria_delete' entrada.id %}">Excluir</a> </td>
            {%endif%}

        </tr>
        {% endfor %}
      </tbody>
    </table>


{% endblock %}

produto/templates/produto/produto_confirm_delete.html
<form action="{% url 'delete-produto-confirm' %}" method="POST"> {% csrf_token %}
    <li> Tem certeza disso {{object}}?</li>
    <input type="submit" value='Confirm'</>
</form>

produto/templates/produto/promocao.html

{% extends 'base.html' %}

{% block main %}
<br>
    <h2 class="sub_tito" >&nbsp; PROMOÇÃO
        <a 
            href="#" onclick="document.getElementById('form_up').style.display='block';">
                Adicionar 
        </a>
    </h2>

    <form id="form_up" class='formulario' style="display: none;" action="{% url 'promocao' %}" method="POST" >
        {% csrf_token %}
        <a id="termo_buttao" href="#" onclick="document.getElementById
        ('form_up').style.display='none';"> X</a>
        <p> NOVA PROMOÇÃO</p>

        <hr> 
    <div> 
        <label> Descrição</label> <br>
            <input style=" width:200px;"  placeholder=" Descrição..." type="text"
                id="descricao" name="descricao"  required/>
    </div>
    <div>
        <label> Desconto a partir</label>  <br>
            <input style=" width:120px;" autofocus="autofocus" placeholder=" Digite a quantidade..."
                type="text" id="quantidade_promocional" name="quantidade_promocional" required/>
    </div>
    <div>
        <label> Desconto</label> <br>
            <input style=" width:220px;"  placeholder="Em porcentagem, Ex: 0,00%" type="number" step=".01" lang="nb"
                id="desconto" name="desconto"  required/>
    </div>
    <div>
        <label> Data de iníco</label> <br>
            <input style=" width:150px; padding:3px;"type="date" id="myDate" name="data_inicio"
                required/>
    </div>
    <div>
        <label> Data de termino</label> <br>
            <input style=" width:150px; padding:3px;" type="date" id="data_termino"
                name="data_termino"  required/>
    </div>
            <hr>
        <button type="submit"> Salvar</button>
    </form>


<br>
<!-- Tabela de produtos -->
    <table class="table">
     <thead>
        <tr>
          <th class="col_table" >Descrição </th>
          <th >Desconto a partir</th>
          <th >Desconto promocional</th>
          <th  >Data de iníco</th>
          <th >Data de termino</th>
           <th > Ação</th>
          
        </tr>
    </thead>
        <tbody>
            {% for promocao in promocao %}
                <tr>
                    <td class="col_table">{{ promocao.descricao}}</td>
                    <td>{{ promocao.quantidade_promocional | floatformat:2}}</td>
                    <td>{{ promocao.desconto | floatformat:2}}%</td>
                    <td>{{ promocao.data_inicio | date:'d/m/y'}}</td>
                    <td>{{ promocao.data_termino | date:'d/m/y'}}</td>

                    {% if perms.produto.change_promocao %}
                        <td> <a href="{% url 'promocao-update' promocao.id %} ">Editar</a> 
                    {% endif %}

                    {% if perms.produto.delete_promocao %}
                        <a href="{% url 'promocao_delete' promocao.id %} ">Excluir</a> </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}